config/routes.rb
Delta::Application.routes.draw do

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  root 'index#index'
  match '/services/:alias', to: 'services#show', via: 'get'
  match '/contacts', to: 'contacts#index', via: 'get'
  resources :reviews, :only => [:index, :create]
  resources :calls, :only => [:create]
  resources :orders, :only => [:create]

  namespace :admin do

    resources :sessions, only: [:new, :create, :destroy]
    root 'sessions#new'
    get '/login' => 'sessions#new'
    match '/logout', to: 'sessions#destroy', via: "delete"

    resources :users
    resources :services
    resources :settings
    resources :prices
    resources :advices
    resources :products
    resources :reviews
    resources :worktimes
    resources :banners
    resources :calls, only: [:index, :destroy]
    resources :orders
  end

  get '*anything', :controller => 'index', :action  => 'e404'

end

app/models/advice.rb
class Advice < ActiveRecord::Base
  belongs_to :service
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/call.rb
class Call < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :service
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :service
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :service
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :prices
  has_many :advices
  has_many :products
  has_many :orders
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

end

app/models/worktime.rb
class Worktime < ActiveRecord::Base
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_filter :signed_in_user
  layout "admin"

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(reviews_params)
    if @review.save
      redirect_to admin_reviews_path
    else
      render 'new'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(reviews_params)
      redirect_to admin_reviews_path
    else
      render 'edit'
    end
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to admin_reviews_path
  end

  private

    def reviews_params
      params.require(:review).permit(:name, :email, :review_text, :image, :published)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Admin::SessionsHelper
  include WorktimesHelper
  before_action :init_menu

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  private

    def init_menu
      @services = Service.where(:parent_id => nil).order('created_at ASC')
    end

end

app/controllers/calls_controller.rb
require 'net/http'
require 'json'
class CallsController < ApplicationController

  def create
    @call = Call.new(call_params)
    uri = URI.parse("https://www.google.com/recaptcha/api/siteverify?secret=6LdtrQETAAAAABXZCGNyMDkIc6sopLGWVja-_wy3&response="+params['g-recaptcha-response'])
    response = Net::HTTP.get_response(uri)
    content = response.body
    h = JSON.parse content
    if (h["success"].to_s == "true")
      if @call.save
        MainMailer.call_mail(@call).deliver
      end
    end
    render :text => h["success"]
  end

  private

    def call_params
      params.require(:call).permit(:name, :phone)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index

  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    @reviews = Review.where(:published => true)
    @banners = Banner.all.order("position ASC")
  end

  def e404
    render :status => '404'
  end

end

app/controllers/orders_controller.rb
require 'net/http'
require 'json'
class OrdersController < ApplicationController

  def create
    @order = Order.new(order_params)
    uri = URI.parse("https://www.google.com/recaptcha/api/siteverify?secret=6LeOrgETAAAAADLDAsZ970EbRi1gOsZFahpASRFM&response="+params['g-recaptcha-response'])
    response = Net::HTTP.get_response(uri)
    content = response.body
    h = JSON.parse content
    if (h["success"].to_s == "true")
      if @order.save
        MainMailer.order_mail(@order).deliver
      end
    end
    render :text => h["success"]
  end

  private

    def order_params
      params.require(:order).permit(:name, :note, :phone, :service_id)
    end

end

app/controllers/reviews_controller.rb
require 'net/http'
require 'json'

class ReviewsController < ApplicationController

  def index
    @reviews = Review.where(:published => true)
  end

  def create
    @review = Review.new(reviews_params)
    uri = URI.parse("https://www.google.com/recaptcha/api/siteverify?secret=6Ld2sAETAAAAADeTTQ_lctaSGbckvTdXrDRJxHZr&response="+params['g-recaptcha-response'])
    response = Net::HTTP.get_response(uri)
    content = response.body
    h = JSON.parse content
    if (h["success"].to_s == "true")
      if @review.save
        MainMailer.review_mail(@review).deliver
      end
    end
    render :text => h["success"]
  end

  private

    def reviews_params
      params.require(:review).permit(:name, :email, :review_text, :image, :published)
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
    @service = Service.find_by(:alias => params[:alias])
    if !@service.nil?
      @children_services = Service.where(:parent_id => @service.id).order("created_at ASC")
      @reviews = Review.where(:published => true)
    else
      render "index/e404", :status => '404'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/worktimes_helper.rb
module WorktimesHelper
  def get_current_worktime
    worktime_value = Worktime.find_by(:alias => 'Special').value
    if worktime_value.empty?
      days = %w{ Sun Mon Tue Wed Thu Fri Sat }
      day_name = days[Time.now.strftime("%w").to_i]
      worktime_value = Worktime.find_by(:alias => day_name)
      if !worktime_value.nil?
        worktime_value = worktime_value.value
      end
    end
    worktime_value
  end
end

app/views/admin/reviews/_review.html.slim
tr
  td
    = review.name
  td
    - if review.email.empty?
      | —
    - else
      = review.email
  td
    - if review.published
      | Да
    - else
      | Нет
  td
    = link_to [:edit, :admin, review]
      button type="button" class="btn btn-sm btn-success"
        | Редактировать
  td
    = link_to "Удалить", [:admin, review], method: :delete, data: { confirm: "Вы уверены, что хотите удалить запись?" }, :class => "btn btn-sm btn-danger"

app/views/admin/reviews/edit.html.slim
h3 Карточка отзыва
- unshow = true
= form_for [:admin, @review] do |f|

  div.input-group
    span class="input-group-addon"
      | Имя посетителя
    = f.text_field :name, :class => 'form-control'

  div.input-group
    span class="input-group-addon"
      | Электронная почта
    = f.text_field :email, :class => 'form-control'

  div.input-group
    span class="input-group-addon"
      | Текст отзыва
    = f.text_area :review_text, :class => 'form-control'

  div.input-group
    span class="input-group-addon"
      | Изображение 130px на 130px
    = f.file_field :image, :class => 'form-control'

  div.input-group
    div.input-group
      span class="input-group-addon"
        | Опубликован
        = f.check_box :published

  = f.submit "Обновить", :class => "btn btn-default"

app/views/admin/reviews/index.html.slim
h3 Список отзывов
div.btns
  = link_to "Создать отзыв", new_admin_review_path, :class => "btn btn-primary"
.panel.panel-default
  table.table
    thead
      tr
        th Имя посетителя
        th Электронная почта
        th Опубликован
    tbody
      = render @reviews

app/views/admin/reviews/new.html.slim
h3 Карточка отзыва
- unshow = true
= form_for [:admin, @review] do |f|

  div.input-group
    span class="input-group-addon"
      | Имя посетителя
    = f.text_field :name, :class => 'form-control'

  div.input-group
    span class="input-group-addon"
      | Электронная почта
    = f.text_field :email, :class => 'form-control'

  div.input-group
    span class="input-group-addon"
      | Текст отзыва
    = f.text_area :review_text, :class => 'form-control'

  div.input-group
    span class="input-group-addon"
      | Изображение 130px на 130px
    = f.file_field :image, :class => 'form-control'

  div.input-group
    div.input-group
      span class="input-group-addon"
        | Опубликован
        = f.check_box :published

  = f.submit "Создать", :class => "btn btn-default"